name: env_isage
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - PyQt6
  - matplotlib
  - scikit-learn
  - torch
  - torchvision
  - pip
  - pip:
      - requests
      - pyyaml
      - sympy
platforms:
  - linux-64
  - osx-arm64
  - win-64
