name: env_isage
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pyqt = 6
  - matplotlib
  - scikit-learn
  - sphinx_rtd_theme
  - pip
  - pip:
      - requests
      - pyyaml
      - sympy
